services:
    # entity.listener.s3injector:
    #     class: AppBundle\Service\EntityS3Injector
    #     arguments:
    #         - '@aws.s3'
    #     tags:
    #         - { name: doctrine.event_listener, event: postLoad }

    exporter.invoices:
        class: AppBundle\Admin\Exporter\InvoiceWriter
        arguments:
            - "@templating"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Basket')"
        tags:
            - { name: sonata.exporter.writer, label: exporter.invoices }

    AppBundle\Repository\BasketRepository:
        factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
        arguments:
            - AppBundle\Entity\Basket

    admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments:
            - ~
            - AppBundle\Entity\Product
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: product.name }

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments:
            - ~
            - AppBundle\Entity\Category
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: category.name }       

    admin.franchise:
        class: AppBundle\Admin\FranchiseAdmin
        arguments:
            - ~
            - AppBundle\Entity\Franchise
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: franchise.name }

    admin.media:
        class: AppBundle\Admin\MediaAdmin
        arguments:
            - ~
            - AppBundle\Entity\Media
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: media.name }

    admin.price:
        class: AppBundle\Admin\PriceAdmin
        arguments:
            - ~
            - AppBundle\Entity\Price
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: price.name }

    admin.sliderimage:
        class: AppBundle\Admin\SliderImageAdmin
        arguments:
            - ~
            - AppBundle\Entity\SliderImage
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: media.name }

    admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments:
            - ~
            - AppBundle\Entity\Client
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: client.name }

    admin.address:
        class: AppBundle\Admin\AddressAdmin
        arguments:
            - ~
            - AppBundle\Entity\Address
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: address.name }

    admin.brand:
        class: AppBundle\Admin\BrandAdmin
        arguments:
            - ~
            - AppBundle\Entity\Brand
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: brand.name }

    admin.ecommerce_configuration:
        class: AppBundle\Admin\ConfigurationAdmin
        arguments:
            - ~
            - AppBundle\Entity\Configuration
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: test, label: configuration.name }

    admin.company:
        class: AppBundle\Admin\CompanyAdmin
        arguments:
            - ~
            - AppBundle\Entity\Company
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: test, label: company.name }

    admin.web:
        class: AppBundle\Admin\WebAdmin
        arguments:
            - ~
            - AppBundle\Entity\Web
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: web.name }

    admin.orders:
        class: AppBundle\Admin\OrderAdmin
        arguments:
            - ~
            - AppBundle\Entity\Basket
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: order.name }
