version: '2'
services:
  php:
      image: danielanteloagra/aldryn
      ports:
          - 9000:9000
  nginx:
      image: nginx
      ports:
          - "8080:80"
      volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
      volumes_from:
          - php
      links:
          - php

