# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Client:
            algorithm: plaintext

    providers:
        client_provider:
            entity:
                class: AppBundle\Entity\Client
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: client_provider

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path:  login
                check_path:  login
                use_referer: true

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/mi-cuenta, roles: ROLE_USER }
