ecommerce:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

intranet:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /intranet

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
